### ISSUE TITLE
image-path is not expanded in the stylesheet

### ISSUE THREAD

**Issue by madx** [nragaz/tipsy-rails#3]
I'm using tipsy-rails 1.0.3 with sass-rails 3.2.5 (sass 3.1.19) and I've noticed that the small black triangles were missing.

The resulting CSS looks like:

``` css
.tipsy-arrow {
  position: absolute;
  background: url(image-path("tipsy/tipsy.gif")) no-repeat top left;
  width: 9px;
  height: 5px; }
```

The position of the last `}` hints that compilation is actually done, but I don't get why the `image-path` call is not expanded.

I don't really know if it is a tipsy-rails issue or if it's sass-rails and I could use a little help about this :-)
